* Clone this repo to the target server: `git clone https://github.com/alexarnoldy/opensuse-chrony-container.git && cd opensuse-chrony-container`
* Update the chrony.conf files as needed 
** At a minimum update the "allow" line for the subnet to monitor and respond on
* Build the container: `sudo podman build -t localhost/opensuse-chrony-container:latest .`


* Set this variable to the IP address chrony should listen on: `export CHRONY_IP=`
* Run the container:
----
sudo podman run -d --name opensuse-chrony-container \
-p ${CHRONY_IP}:123:123/udp \
--cap-add=NET_ADMIN \
--net host \
--cap-add SYS_TIME \
localhost/opensuse-chrony-container:latest
----

IMPORTANT: There were lots of problems with chronyd refusing to start after system reboot due to the presence of a PID file. A PID file doesn't make much sense in the case of a container so script just removes it before starting chronyd. The disadvantage is that it seems to automatically restart when trying to stop it. To stop it, just string together stop and rm commands; then run it again as above, when needed.

* Ensure the container is running: `sudo podman ps -a`
** The "STATUS" field should show the amount of time the container has been running
** If the STATUS is EXITED, run the command `sudo podman logs opensuse-chrony-container` to see the error that stopped the container
* Ensure that port 123 is being monitored: `ss -npr --listening`

==== Configure the chrony container to start on boot
* Copy the opensuse-chrony.service systemd file into place: `sudo cp -p opensuse-chrony.service /etc/systemd/system/`
* Reload systemd: `sudo systemctl daemon-reload`
* Start and enable the systemd opensuse-chrony.service: `sudo systemctl --now enable opensuse-chrony.service`
* Check the status of the opensuse-chrony.service: `systemctl status opensuse-chrony.service`


==== To update the chrony configuration
* Update the chrony.conf file
* Rebuild the image
* Remove the old container and run a new one

==== Troubleshooting
* Ensure a server firewall isn’t blocking the ports (Google for how to work with your firewall)
* From another host in the same subnet, use nmap to see if chrony is responding: `sudo nmap -sU -p 123 --script ntp-info <chrony server IP>`
** At a minimum response containing the "receive time stamp" should be received




// vim: set syntax=asciidoc:
